package JOGO;

import java.awt.Color;
import java.awt.Image;
import java.awt.Label;
import java.awt.event.MouseEvent;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Guilherme
 */

public class FrCartas extends javax.swing.JFrame {

    /** Creates new form FrCartas */
    public FrCartas() {
        initComponents();
         // carregar o formulário no centro da tela
        setLocationRelativeTo(this);
        // desativa o redirecionamento do formulario
        setResizable (false);
        // atribui titulo ao formulário
        setTitle("cartas!");
        //Imagem Logo
        ImageIcon logo = new ImageIcon(getClass().getResource("LOGOSHOW.jpg"));
        jLogo.setIcon(new ImageIcon(logo.getImage().getScaledInstance(jLogo.getWidth(),jLogo.getHeight(),Image.SCALE_SMOOTH)));
        
        //Imagem Carta 1
        ImageIcon carta = new ImageIcon(getClass().getResource("CARTA.jpg"));
        lblCarta1.setIcon(new ImageIcon(carta.getImage().getScaledInstance(lblCarta1.getWidth(),lblCarta1.getHeight(),Image.SCALE_SMOOTH)));
        lblCarta1.getAccessibleContext().setAccessibleName("1");
        //Imagem Carta 2
        ImageIcon carta2 = new ImageIcon(getClass().getResource("CARTA.jpg"));
        lblCarta2.setIcon(new ImageIcon(carta2.getImage().getScaledInstance(lblCarta2.getWidth(),lblCarta2.getHeight(),Image.SCALE_SMOOTH)));
        lblCarta2.getAccessibleContext().setAccessibleName("2");        
        //Imagem Carta 3
        ImageIcon carta3 = new ImageIcon(getClass().getResource("CARTA.jpg"));
        lblCarta3.setIcon(new ImageIcon(carta3.getImage().getScaledInstance(lblCarta3.getWidth(),lblCarta3.getHeight(),Image.SCALE_SMOOTH)));
        lblCarta3.getAccessibleContext().setAccessibleName("3");        
        //Imagem Carta 4
        ImageIcon carta4 = new ImageIcon(getClass().getResource("CARTA.jpg"));
        lblCarta4.setIcon(new ImageIcon(carta4.getImage().getScaledInstance(lblCarta4.getWidth(),lblCarta4.getHeight(),Image.SCALE_SMOOTH)));
        lblCarta4.getAccessibleContext().setAccessibleName("4");
        
        lblClique.setVisible(false);
    }
    
   // private void inibirResposta(MouseEvent evt){
    //   Label lbl = (Label) evt.getSource(); 
   
   //}
    
    public static int inibir;
  
    private void virarCartas(String valor1){
       Random gerador = new Random();
       int nrandomico = gerador.nextInt(4);
       String carta="";   
       ImageIcon cartas;
       switch(nrandomico){
            case 0:
                carta ="CARTA 00.png";
                break;
            case 1:
                carta ="CARTA 01.png";
                break;
            case 2:
                carta ="CARTA 02.png";
                break;
            case 3:
                carta ="CARTA 03.png";
                break;
       } 
       inibir = nrandomico;
       cartas = new ImageIcon(getClass().getResource(carta));
        
        switch(valor1){
            case "1":               
                lblCarta1.setIcon(new ImageIcon(cartas.getImage().getScaledInstance(lblCarta1.getWidth(),lblCarta1.getHeight(),Image.SCALE_SMOOTH)));
                break;
                
            case "2":
                lblCarta2.setIcon(new ImageIcon(cartas.getImage().getScaledInstance(lblCarta2.getWidth(),lblCarta2.getHeight(),Image.SCALE_SMOOTH)));
                break;
                
            case "3":
                lblCarta3.setIcon(new ImageIcon(cartas.getImage().getScaledInstance(lblCarta3.getWidth(),lblCarta3.getHeight(),Image.SCALE_SMOOTH)));
                break;
                
            case "4":
                lblCarta4.setIcon(new ImageIcon(cartas.getImage().getScaledInstance(lblCarta4.getWidth(),lblCarta4.getHeight(),Image.SCALE_SMOOTH)));
                break;
       }
        lblClique.setText("Você conseguiu esconder " + nrandomico + " respostas. ");
        lblClique.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        lblClique = new javax.swing.JLabel();
        lblCarta1 = new javax.swing.JLabel();
        lblCarta2 = new javax.swing.JLabel();
        lblCarta3 = new javax.swing.JLabel();
        lblCarta4 = new javax.swing.JLabel();
        lblRetorno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(1, 1, 28));

        lblClique.setBackground(new java.awt.Color(0, 0, 0));
        lblClique.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblClique.setForeground(new java.awt.Color(255, 255, 255));
        lblClique.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClique.setText("Clique Aqui para retornar ao Jogo.");
        lblClique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCliqueMouseClicked(evt);
            }
        });

        lblCarta1.setBackground(new java.awt.Color(255, 51, 51));
        lblCarta1.setForeground(new java.awt.Color(255, 255, 255));
        lblCarta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarta1MouseClicked(evt);
            }
        });

        lblCarta2.setForeground(new java.awt.Color(255, 255, 255));
        lblCarta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarta2MouseClicked(evt);
            }
        });

        lblCarta3.setForeground(new java.awt.Color(255, 255, 255));
        lblCarta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarta3MouseClicked(evt);
            }
        });

        lblCarta4.setForeground(new java.awt.Color(255, 255, 255));
        lblCarta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarta4MouseClicked(evt);
            }
        });

        lblRetorno.setBackground(new java.awt.Color(0, 0, 0));
        lblRetorno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRetorno.setForeground(new java.awt.Color(255, 255, 255));
        lblRetorno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetorno.setText("Escolha uma Carta!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClique, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCarta3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(lblCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarta4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(55, 55, 55))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarta4, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addComponent(lblClique, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(lblRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean entrou = false;
    
    private void lblCarta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarta1MouseClicked
     //   inibirResposta(evt);
        if (!entrou) {
           String valor = lblCarta1.getAccessibleContext().getAccessibleName();
           lblCarta3.setEnabled(false); 
           lblCarta2.setEnabled(false); 
           lblCarta4.setEnabled(false); 
           virarCartas(valor);
           entrou = true;
        }
       
    }//GEN-LAST:event_lblCarta1MouseClicked

    private void lblCarta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarta2MouseClicked
    //    inibirResposta(evt);
       if (!entrou) { 
       String valor = lblCarta2.getAccessibleContext().getAccessibleName();
       lblCarta1.setEnabled(false); 
       lblCarta3.setEnabled(false); 
       lblCarta4.setEnabled(false);  
       virarCartas(valor); 
       entrou = true;
    }//GEN-LAST:event_lblCarta2MouseClicked
    }
    private void lblCarta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarta3MouseClicked
     //   inibirResposta(evt);
       if (!entrou) {
       String valor = lblCarta3.getAccessibleContext().getAccessibleName(); 
       lblCarta1.setEnabled(false); 
       lblCarta2.setEnabled(false); 
       lblCarta4.setEnabled(false); 
       virarCartas(valor);
       entrou = true;
    }//GEN-LAST:event_lblCarta3MouseClicked
    }
    private void lblCarta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarta4MouseClicked
     //  inibirResposta(evt);
        if (!entrou) {
       String valor = lblCarta4.getAccessibleContext().getAccessibleName();
       lblCarta1.setEnabled(false); 
       lblCarta2.setEnabled(false); 
       lblCarta3.setEnabled(false);        
       virarCartas(valor);
       entrou = true;
    }//GEN-LAST:event_lblCarta4MouseClicked
    }
    private void lblCliqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCliqueMouseClicked
    
        this.dispose();
        // trocando a tela para modo jogo
        new FrJogo().setVisible(true);
        


    }//GEN-LAST:event_lblCliqueMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCarta1;
    private javax.swing.JLabel lblCarta2;
    private javax.swing.JLabel lblCarta3;
    private javax.swing.JLabel lblCarta4;
    private javax.swing.JLabel lblClique;
    private javax.swing.JLabel lblRetorno;
    // End of variables declaration//GEN-END:variables

}
